### ISSUE TITLE
Mentor Roll Call!  -  2017 May 6th, NodeSchool @Codesmith

### ISSUE THREAD

**Issue by rouzbeh84** [nodeschool/los-angeles#109]
This May 6th, NodeSchool will be at CodeSmith and we will be going over [`learnyounode`](https://github.com/workshopper/learnyounode). 

It will be from **2-5pm** and you can register here on [ti.to](https://ti.to/nodeschool-los-angeles/may-2017) as a mentor 

Are you in??

### Confirmed
- [x] @rouzbeh84
- [x] @etanlubeck 
- [x] @jarrettch 

### Maybe
- [ ] @d48
- [ ] @jcblw

### Hopefully 
- [ ] you?

**Comment by ashwell** [comment]
I think @etanlubeck is confirmed since he already put his name on the mentor list on the README.

I don't think I'm going to make it to this one, need a break after last month.

**Comment by rouzbeh84** [comment]
Cool, marking you off @etanlubeck but please confirm as well

**Comment by jarrettch** [comment]
I should be able to make it for this one.

**Comment by rouzbeh84** [comment]
Awesome! added you to the list, thanks!
