### ISSUE TITLE
Mentor Roll Call! - 2017 June 3rd, NodeSchool @Codesmith

### ISSUE THREAD

**Issue by rouzbeh84** [nodeschool/los-angeles#113]
This May 6th, NodeSchool will be at CodeSmith and we will be going over [`learnyounode`](https://github.com/workshopper/learnyounode). 

It will be from **2-5pm** and you can register here on [ti.to](https://ti.to/nodeschool-los-angeles/june-2017) as a mentor 

Are you in??

### Confirmed
- [x] @remarks 
- [x] @jarrettch 
- [x] @alice-em 
- [x] @robawilkinson
- [x] @josh91hickman
- [x] @rouzbeh84

### Maybe

- [ ] @ashwell 
- [ ] @etanlubeck 
- [ ] @d48
- [ ] @jcblw

### Hopefully 
- [ ] you?

**Comment by alice-em** [comment]
@alice-em maybe

**Comment by jarrettch** [comment]
Count me in!

**Comment by alice-em** [comment]
I'll be there! :3

**Comment by remarks** [comment]
🙋‍♂️ I'd like to come help as well!

**Comment by RobAWilkinson** [comment]
I'll be there!

**Comment by ashwell** [comment]
If it is your first time mentoring be sure to check out issue #112 for the event structure
