### ISSUE TITLE
Mentor Roll Call! - 2017 July 1st, NodeSchool @Codesmith

### ISSUE THREAD

**Issue by rouzbeh84** [nodeschool/los-angeles#115]
This July 1st, NodeSchool will be at CodeSmith and we will be going over [`learnyounode`](https://github.com/workshopper/learnyounode). 

It will be from **2-5pm** and you can register here on [ti.to](https://ti.to/nodeschool-los-angeles/july-2017) as a mentor 

Are you in??

### Confirmed
- [x] @rouzbeh84
- [x] @jarrettch 
- [x] @etanlubeck 

### Maybe

- [x] @ashwell 
- [ ] @d48
- [ ] @jcblw
- [ ] @remarks 
- [ ] @robawilkinson
- [ ] @josh91hickman

### Hopefully 
- [ ] you?

**Comment by rouzbeh84** [comment]
Anybody interested? We still have an open slate for mentors on this one.

- [ ] @ashwell 
- [ ] @etanlubeck 
- [ ] @d48
- [ ] @jcblw
- [ ] @remarks 
- [ ] @jarrettch 
- [ ] @alice-em 
- [ ] @robawilkinson
- [ ] @josh91hickman

**Comment by alice-em** [comment]
I won't be able to make this one.

**Comment by rouzbeh84** [comment]
Thanks for the heads up @alice-em! Catch you next time hopefully 👍

**Comment by alice-em** [comment]
Totally!  Keep me in the loop.

**Comment by ashwell** [comment]
@rouzbeh84 you can put me down as a maybe, I'll confirm by the end of the week if I'll be available

**Comment by jarrettch** [comment]
I'm a maybe as well. My daughter's 3rd bday is Sunday, not sure if I'll do something Saturday or Sunday for her yet but will know for sure later in the week.

**Comment by rouzbeh84** [comment]
Big thanks to @jarrettch @etanlubeck (possibly @ashwell haha)!

Anybody else interested?
