### ISSUE TITLE
Mentor Roll Call! - 2017 August 5th, NodeSchool @Codesmith

### ISSUE THREAD

**Issue by rouzbeh84** [nodeschool/los-angeles#119]
This **August 5th**, NodeSchool will be at CodeSmith and we will be going over [`learnyounode`](https://github.com/workshopper/learnyounode). 

It will be from **2-5pm** and you can register here on [eventbrite](https://www.eventbrite.com/e/nodeschool-la-tickets-36372151083?aff=git) as a mentor 

Are you in??

### Confirmed
- [x] @rouzbeh84
- [x] @ashwell
- [ ] @etanlubeck 
- [x] @jarrettch 

### Maybe

- [ ] @d48
- [ ] @jcblw
- [ ] @remarks 
- [ ] @robawilkinson
- [ ] @josh91hickman

### Maybe... 
- [ ] you?

**Comment by ashwell** [comment]
@rouzbeh84 @etanlubeck 

updated this, go ahead and check your name off to confirm

**Comment by jarrettch** [comment]
I'll be there.
