### ISSUE TITLE
location for the next event

### ISSUE THREAD

**Issue by d48** [nodeschool/los-angeles#12]
Hey everyone,
just wondering if anyone knows a place that is willing to donate space for the next NodeSchool event. I've reached out to co-loft and ctrl.la but no response yet.

**Comment by aktary** [comment]
I bet Codesmith.io would do it.  Also, check out CTRL Collective... not
sure they'd do it for free though.

Regards,

David Aktary

**Comment by aktary** [comment]
I just spoke with Will at Codesmith and he's interested.  I told him to
look for an email from you. You can reach him at: william.sentance@gmail.com


Regards,

David Aktary

**Comment by d48** [comment]
nice! checking if my work would sponsor a place and food too as another option. I'll look out for Will's email

**Comment by aktary** [comment]
Will is waiting to hear from you. 

- David

**Comment by d48** [comment]
Great, I emailed him

**Comment by d48** [comment]
awesome, we are locked in for a date and time at Codesmith!

July 25, 2pm - 4pm

Just need to find a food/drink sponsor and let's do this. Thanks for the contact @aktary!
