### ISSUE TITLE
Mentor Roll Call! - 2017 September 2nd, NodeSchool @Codesmith

### ISSUE THREAD

**Issue by ashwell** [nodeschool/los-angeles#123]
This **September 2nd**, NodeSchool will be at CodeSmith and we will be going over [`learnyounode`](https://github.com/workshopper/learnyounode). 

It will be from **2-5pm** and you can register here on [eventbrite](https://nodeschoolla.eventbrite.com?aff=git) as a mentor 

Are you in??

### Confirmed
- [ ] you?
- [x] @jarrettch 

### Maybe
- [ ] @rouzbeh84
- [x] @ashwell
- [ ] @etanlubeck 
- [ ] @d48
- [ ] @jcblw
- [ ] @remarks 
- [ ] @robawilkinson
- [ ] @josh91hickman
- [ ] you?

**Comment by jarrettch** [comment]
I'll be there!

**Comment by rouzbeh84** [comment]
samesies

**Comment by rouzbeh84** [comment]
whoa, j/k. just remembered have a wedding to go to
