### ISSUE TITLE
Mentor Roll Call! - 2017 October 7th

### ISSUE THREAD

**Issue by ashwell** [nodeschool/los-angeles#127]
This **October 2nd**, NodeSchool will be at CodeSmith and we will be going over [`learnyounode`](https://github.com/workshopper/learnyounode). 

It will be from **2-5pm** and you can register here on [eventbrite](https://nodeschoolla.eventbrite.com?aff=git) as a mentor 

Are you in??

### Confirmed
- [x] @seanwestfall
- [x] @rouzbeh84
- [x] @jarrettch 
- [ ] you?

### Maybe 
- [ ] @d48
- [ ] @jcblw
- [ ] @remarks 
- [ ] @robawilkinson
- [ ] you?

**Comment by josh91hickman** [comment]
@ashwell count me in

**Comment by rouzbeh84** [comment]
I'm down! Will double check but most likely can make it.

@jarrettch you in? i can bring that monitor too if we both end up there 👍
