### ISSUE TITLE
Need food/drink sponsor for next event July 25, 2pm - 4pm

### ISSUE THREAD

**Issue by d48** [nodeschool/los-angeles#13]
We have a location and date locked in for Saturday, July 25. Anyone know of individual/company interested in sponsoring?

**Comment by 8bitDesigner** [comment]
I'm chatting with some peeps at Fullscreen; will let you know.

**Comment by d48** [comment]
:+1:

**Comment by d48** [comment]
Confirmed, Fullscreen is sponsoring 💥
