### ISSUE TITLE
Mentor Roll Call! - January 6th, 2018

### ISSUE THREAD

**Issue by jarrettch** [nodeschool/los-angeles#143]
This **January 6th**, NodeSchool will be at **Codesmith** and we will be going over [`learnyounode`](https://github.com/workshopper/learnyounode). 

It will be from **2-5pm** and you can register here on [eventbrite](https://nodeschoolla.eventbrite.com?aff=git) as a mentor 

Are you in??

### Confirmed
- [x] @jarrettch 
- [ ] you?

### Maybe 
- [ ] @seanwestfall
- [ ] @rouzbeh84 
- [ ] @ashwell
- [ ] @josh91hickman
- [ ] @d48
- [ ] @jcblw
- [ ] @remarks 
- [ ] @robawilkinson
- [ ] you?

**Comment by rouzbeh84** [comment]
cc: @gr2m to add to future possible mentors 👍

**Comment by jarrettch** [comment]
Thanks @rouzbeh84 will do. Need to prune this list anyway.
