### ISSUE TITLE
Mentor Roll Call! - February 3rd, 2018

### ISSUE THREAD

**Issue by jarrettch** [nodeschool/los-angeles#147]
This **Saturday February 3rd**, NodeSchool will be at **Codesmith** and we will be going over [`learnyounode`](https://github.com/workshopper/learnyounode). 

It will be from **2-5pm** and you can register here on [Eventbrite](https://nodeschoolla.eventbrite.com?aff=git) as a mentor 

Are you in??

### Confirmed
- [x] @jarrettch
- [ ] you?

### Maybe 
- [ ] @rouzbeh84
- [ ] @seanwestfall
- [ ] @ashwell
- [ ] @d48
- [ ] @jcblw 
- [ ] you?

_edited date on 01/24 by @rouzbeh84_

**Comment by gr2m** [comment]
I’ve put it on my calendar :)

**Comment by gr2m** [comment]
How many folks do you expect? Do you have a location yet?

**Comment by ashwell** [comment]
@gr2m forgot to update the ticket, the website is right though. Nodeschool will be at Codesmith

we typically get 12 to 15 people

**Comment by rouzbeh84** [comment]
Yea that’s roughly right. We had a really good showing for January though with I think 19/20 folks there

**Comment by jarrettch** [comment]
Yup, sorry about any confusion. Ticket updated.

**Comment by gr2m** [comment]
the issue says Feb 2, the website says Feb 3, which one is right?

**Comment by rouzbeh84** [comment]
2/3 is correct. The Saturday. Will fix ASAP

**Comment by gr2m** [comment]
so sorry folks but  I can’t make it on the Saturday, I’ll be at https://www.eventbrite.com/e/want-to-speak-at-a-tech-conference-global-diversity-cfp-day-los-angeles-tickets-42255541462

**Comment by jarrettch** [comment]
No worries, enjoy the the event!
