### ISSUE TITLE
Mentor Roll Call! - Saturday April 7th, 2018

### ISSUE THREAD

**Issue by jarrettch** [nodeschool/los-angeles#154]
On **Saturday April 7th**, NodeSchool will be at **Codesmith** and we will be going over [`learnyounode`](https://github.com/workshopper/learnyounode). 

It will be from **2-5pm** and you can register here on [Eventbrite](https://nodeschoolla.eventbrite.com?aff=git) as a mentor 

Are you in??

### Confirmed
- [x] @jarrettch
- [ ] you?

### Maybe 
- [ ] @rouzbeh84
- [ ] @seanwestfall
- [ ] @ashwell
- [ ] @d48
- [ ] @jcblw 
- [ ] @gr2m
- [ ] you?

**Comment by gr2m** [comment]
hey sorry I won’t be able to make it again, I’ll be on  vacation

**Comment by aaa-ace** [comment]
All good @gr2m thanks for letting me know. Enjoy the vacay!

**Comment by jarrettch** [comment]
All good man, thanks for letting me know. Enjoy the vacay!
