### ISSUE TITLE
Mentor Roll Call! - Saturday June 2nd, 2018

### ISSUE THREAD

**Issue by jarrettch** [nodeschool/los-angeles#165]
On **Saturday June 2nd**, NodeSchool will be at **Codesmith** and we will be going over [`learnyounode`](https://github.com/workshopper/learnyounode). 

It will be from **2-5pm** and you can register here on [Eventbrite](https://nodeschoolla.eventbrite.com?aff=git) as a mentor 

Are you in??

### Confirmed
- [x] @jarrettch
- [ ] you?

### Maybe 
- [ ] @rouzbeh84
- [ ] @seanwestfall
- [ ] @ashwell
- [ ] @d48
- [ ] @jcblw 
- [ ] @gr2m
- [ ] @shockey 
- [ ] you?

**Comment by shockey** [comment]
@jarrettch, I can't pitch in on the 2nd but please put me on the maybe list for future events! 😄

**Comment by gr2m** [comment]
Sorry can’t make it the next 3 months at least

**Comment by jarrettch** [comment]
@shockey alright, added you to the list and hopefully see ya in July!

@gr2m no worries man!
