### ISSUE TITLE
Mentor Roll Call! - Saturday July 7th, 2018

### ISSUE THREAD

**Issue by jarrettch** [nodeschool/los-angeles#172]
On **Saturday July 7th**, NodeSchool will be at **Replicated** and we will be going over [`learnyounode`](https://github.com/workshopper/learnyounode). 

It will be from **2-5pm** and you can register here on [Eventbrite](https://nodeschoolla.eventbrite.com?aff=git) as a mentor 

Are you in??

### Confirmed
- [x] @jarrettch
- [ ] you?

### Maybe 
- [ ] @rouzbeh84
- [ ] @seanwestfall
- [ ] @ashwell
- [ ] @d48
- [ ] @jcblw 
- [ ] @gr2m
- [ ] @shockey 
- [ ] you?

**Comment by ashwell** [comment]
heads up I will **not** be at this one
