### ISSUE TITLE
Mentor Roll Call! - Saturday August 4th, 2018

### ISSUE THREAD

**Issue by jarrettch** [nodeschool/los-angeles#176]
On **Saturday August 4th**, NodeSchool will be at **Replicated** and we will be going over [`learnyounode`](https://github.com/workshopper/learnyounode). 

It will be from **2-5pm** and you can register here on [Eventbrite](https://nodeschoolla.eventbrite.com?aff=git) as a mentor 

Are you in??

### Confirmed
- [x] @jarrettch
- [ ] you?

### Maybe 
- [ ] @rouzbeh84
- [ ] @seanwestfall
- [ ] @ashwell
- [ ] @d48
- [ ] @jcblw 
- [ ] @gr2m
- [x] @shockey 
- [ ] you?

**Comment by shockey** [comment]
@jarrettch - forgot to ping you here but I did sign up on Eventbrite, I'll be there tomorrow 👍
