### ISSUE TITLE
Mentor Roll Call! - Saturday September 1st, 2018

### ISSUE THREAD

**Issue by jarrettch** [nodeschool/los-angeles#181]
On **Saturday September 1st**, NodeSchool will be at **Replicated** and we will be going over [`learnyounode`](https://github.com/workshopper/learnyounode). 

It will be from **2-5pm** and you can register here on [Eventbrite](https://nodeschoolla.eventbrite.com?aff=git) as a mentor 

Are you in??

### Confirmed
- [x] @jarrettch
- [x] @MrBenJ
- [ ] you?

### Maybe 
- [ ] @rouzbeh84
- [ ] @seanwestfall
- [ ] @ashwell
- [ ] @d48
- [ ] @jcblw 
- [ ] @gr2m
- [ ] @shockey 
- [ ] you?

**Comment by MrBenJ** [comment]
I'm down!

**Comment by jarrettch** [comment]
Awesome @MrBenJ thanks man!
