### ISSUE TITLE
Mentor Roll Call! - Saturday October 6th, 2018

### ISSUE THREAD

**Issue by jarrettch** [nodeschool/los-angeles#182]
On **Saturday October 6th**, NodeSchool will be at **Replicated** and we will be going over [`learnyounode`](https://github.com/workshopper/learnyounode). 

It will be from **2-5pm** and you can register here on [Eventbrite](https://nodeschoolla.eventbrite.com?aff=git) as a mentor 

Are you in??

### Confirmed
- [x] @jarrettch
- [x] @MrBenJ
- [ ] you?

### Maybe 
- [ ] @rouzbeh84
- [ ] @seanwestfall
- [ ] @ashwell
- [ ] @d48
- [ ] @jcblw 
- [ ] @gr2m
- [ ] @shockey 
- [ ] you?

**Comment by MrBenJ** [comment]
@jarrettch - I'm in. Committing to this now. Hopefully last minute emergencies won't be a thing this time :)
