### ISSUE TITLE
Mentor Roll Call! - Saturday April 6th, 2019

### ISSUE THREAD

**Issue by jarrettch** [nodeschool/los-angeles#197]
On Saturday April 6th, NodeSchool will be at Replicated and we will be going over learnyounode.

It will be from **2-5pm** and you can register here on [Eventbrite](https://nodeschoolla.eventbrite.com?aff=git) as a mentor 

Are you in??

### Confirmed
- [x] @jarrettch
- [ ] you?

### Maybe 
- [ ] @rouzbeh84
- [ ] @shockey 
- [ ] @leggomuhgreggo
- [ ] @seanwestfall
- [ ] @MrBenJ
- [ ] @d48
- [ ] @jcblw 
- [ ] you?

**Comment by gr2m** [comment]
I won’t be able to help anytime soon I’m afraid

**Comment by jarrettch** [comment]
Sorry @gr2m and thanks for the update. I'll remove you from the Mentor List.
