### ISSUE TITLE
Mentor Roll Call! - Saturday July 6th, 2019

### ISSUE THREAD

**Issue by jarrettch** [nodeschool/los-angeles#204]
On Saturday July 6th, NodeSchool will be at Replicated and we will be going over learnyounode.

It will be from **2-5pm** and you can register here on [Eventbrite](https://nodeschoolla.eventbrite.com?aff=git) as a mentor 

Are you in??

### Confirmed
- [x] @jarrettch
- [ ] you?

### Maybe 
- [ ] @rouzbeh84
- [ ] @shockey 
- [ ] @leggomuhgreggo
- [ ] @seanwestfall
- [ ] @MrBenJ
- [ ] you?

**Comment by shockey** [comment]
> Saturday June 1st

@jarrettch 😉

**Comment by jarrettch** [comment]
@shockey D'oh! Thanks lol
