### ISSUE TITLE
Mentor headcount and ticket conformation for Codesmith for July 25 event

### ISSUE THREAD

**Issue by d48** [nodeschool/los-angeles#26]
Hello mentors, just need to know if you all happened to get a https://ti.to/nodeschool-los-angeles/july-2015/ ticket or not so that I know to manually add you to the list that Codesmith needs. Just reply to this thread a yes (:+1:) you got a ticket or no (:-1:) if you didn't get a ticket. Thanks.

@davidguttman
@8bitDesigner
@andyburke
@rynodivino
@paigeful
@aktary
@soldair
@emkay
@xbudex
@dstokes

**Comment by 8bitDesigner** [comment]
:+1: I'm good

**Comment by xbudex** [comment]
I didn't get a ticket.

**Comment by rynodivino** [comment]
I didn't see a ticket.

- Ryan

**Comment by davidguttman** [comment]
I did not get a ticket

**Comment by soldair** [comment]
didn't either

**Comment by emkay** [comment]
nope :(

**Comment by andyburke** [comment]
I did not get a ticket.

**Comment by aktary** [comment]
I didn't get a ticket either.

Regards,

David Aktary

**Comment by paigeful** [comment]
:+1: I think I did.

**Comment by dstokes** [comment]
i didn't get one :(

**Comment by d48** [comment]
Awesome, no worries if you didn't get a ticket. Will be adding your name on the list so Codesmith has it. Side note: we will need to have name tags a different color or marked so attendees know who's a mentor. Thanks guys

**Comment by d48** [comment]
everyone's good and I added them on the list if it was needed. @paigeful, can you message me your name so I can check the list?

**Comment by paigeful** [comment]
@d48 name Paige Ma. Thanks!

**Comment by d48** [comment]
Okay great. You're there



Thank you,
Ryan


{
  "name":   "Ryan Regalado",
  "email":  "ryan.regalado.48@gmail.com",
  "phone":  "(949)-751-9386"
}
