### ISSUE TITLE
Site design, next event.

### ISSUE THREAD

**Issue by jcblw** [nodeschool/los-angeles#27]
Hey yo,

Was in a designing mood and decided to take a shot a design for the nodeschool site. I think it would be good to do this for the next event ( if liked ) since the current is not too far away.

![nodeschool-website-redesign](https://cloud.githubusercontent.com/assets/578259/8634913/d7905a68-27c1-11e5-8a38-9565a41dd31c.png)

would love to hear ideas, criticism.

**Comment by d48** [comment]
duuuuude, this is fantastic! I'm in for this layout for sure and all the colors. My only note would be to add a link to Node.js install, then that step of `npm install ...`. Lastly from the FAQ to be sure to install before the event, and if not, we can help there if they run into issues. 

Super clean :+1:

**Comment by aktary** [comment]
Now that we've got a fancy new site, someone should update the link on the chapters page of nodeschool.io.  Anyone know how?

**Comment by d48** [comment]
@aktary you can create a pull request to update this page and add our .svg to /image dir
https://github.com/nodeschool/nodeschool.github.io/blob/source/hexdex.html

**Comment by d48** [comment]
Let's go with this design, it's great. Here's the info for the next August 22, 2015 event and the sponsor:

Blackline

https://www.blackline.com/company

BlackLine is the first and most experienced provider of enterprise-class software designed to automate and control the entire financial close process. The first BlackLine module was developed when a client, First National Bank of Nebraska, asked BlackLine for help managing their account reconciliation process. Like many companies, they were using spreadsheets to manage thousands of reconciliations every month. In response, BlackLine developed and marketed the first commercially available software designed specifically for tracking and completing balance sheet account reconciliations.

**Comment by jcblw** [comment]
Ok ill look to start migrating this over tonight, optimistically I can make a PR before August.

**Comment by d48** [comment]
:+1:

**Comment by d48** [comment]
note: to add NodeSchool LA's twitter account: https://twitter.com/nodeschoolla

**Comment by jcblw** [comment]
made some huge progress last night https://github.com/jcblw/los-angeles/tree/feature/new-site there some smoothing out that needs to still happen mostly for making a better mobile experience as well as updating info.

**Comment by d48** [comment]
Awesome @jcblw! :clap:

**Comment by jcblw** [comment]
Ok pushed a bit more, way more mobile friendly, icons whatnot.

Im looking to fill in some info for this month

<img width="730" alt="screen shot 2015-07-28 at 11 37 09 pm" src="https://cloud.githubusercontent.com/assets/578259/8951392/27ab373e-3582-11e5-8700-d7ab5d4d3579.png">

As well as I need feed back on what I should do with the footer. The have never been my strong suite.

<img width="841" alt="screen shot 2015-07-28 at 11 37 19 pm" src="https://cloud.githubusercontent.com/assets/578259/8951395/2d82859a-3582-11e5-9091-3f8b2bc92498.png">

**Comment by d48** [comment]
This is great @jcblw! For event details, just get ti.to address listed for Blackline,  and for now just fill in time and date with "More to be determined". I'm finalizing details with a few folks here and I can update once this is live.

For footer, there's really no place that links to this github repo accept through **Open an issue** link above. I'd add another link below Slack that says `Github Repo` and link to https://github.com/nodeschool/los-angeles

Great work

**Comment by d48** [comment]
one other note, what do you think of making the header a logo a little larger so it's more prominent? It looks great how it connects to the 2 colored areas

**Comment by jcblw** [comment]
<img width="558" alt="screen shot 2015-07-29 at 5 13 55 pm" src="https://cloud.githubusercontent.com/assets/578259/8973105/e1126812-3615-11e5-8d9a-cac86a140631.png">

We already have that section!

I see what I can do. I limited the space to 800 i can expand that to 960;

**Comment by d48** [comment]
:+1:

**Comment by d48** [comment]
Great work @jcblw
