### ISSUE TITLE
NodeSchool L.A. 7/25 will be repeated?

### ISSUE THREAD

**Issue by ClawGee** [nodeschool/los-angeles#28]
Hello. I am unable to attend the event thks weekend and was wondering if it'll be repeated in the future?

Thank you!

**Comment by d48** [comment]
Yes, we will have another one August 22. Please send me your name so that I may reassign the ticket if you haven't already done so



Thank you,
Ryan


{
  "name":   "Ryan Regalado",
  "email":  "ryan.regalado.48@gmail.com",
  "phone":  "(949)-751-9386"
}

**Comment by ClawGee** [comment]
Hi Ryan,

My name is Claudia Gonzalez and I'd love to cancel my spot for this weekend
and reserve my spot for the next offering of this session.

Thanks!

Claudia

**Comment by lorensstewart** [comment]
Hey Ryan,




I have to cancel for the 25th, too. I'll be there in August, though!!




Loren Stewart 



—

**Comment by d48** [comment]
Okay great, thanks Claudia! See you next month 



Thank you,
Ryan


{
  "name":   "Ryan Regalado",
  "email":  "ryan.regalado.48@gmail.com",
  "phone":  "(949)-751-9386"
}

**Comment by d48** [comment]
Great, thanks Loren!



Thank you,
Ryan


{
  "name":   "Ryan Regalado",
  "email":  "ryan.regalado.48@gmail.com",
  "phone":  "(949)-751-9386"
}
