### ISSUE TITLE
Need mentors for August 22 Nodeschool Event

### ISSUE THREAD

**Issue by d48** [nodeschool/los-angeles#34]
Need some more mentors for this day. Who's in? Just update the readme on the repo. Thanks!

**Comment by machikoyasuda** [comment]
can you just @ mention any github people here? or only people in this group? 

@boovius @theresaluu

**Comment by theresaluu** [comment]
I think anyone on github cus I have mentioned someone on accident before on a project.  I can't help on that day, sorry FYFest.  =(

**Comment by d48** [comment]
Thanks @machikoyasuda. Will hit up past mentors as well and see

**Comment by d48** [comment]
Mentors from last event, any of you guys in for this month?

@davidguttman 
@8bitDesigner 
@rynodivino
@paigeful
@aktary
@xbudex
@dstokes

**Comment by d48** [comment]
I guess if no mentors by end of day we can just move this to a future date when there are more mentors to support the sign ups. My bad, we should set the date and mentors first before announcing

**Comment by d48** [comment]
We have a set of mentors, yay
