### ISSUE TITLE
Who's in to mentor for September 19?

### ISSUE THREAD

**Issue by d48** [nodeschool/los-angeles#40]
CodeSmith has kindly offered their place again to host. Anyone want to help mentor? Also any ideas of who can sponsor food/drink? I think having 5 mentors works perfect for the average amount of attendees that have been coming out, but the more the merrier as well!

Confirmed:
- [x] @jcblw 
- [x] @davidguttman 
- [x] @andyburke 
- [ ] @emkay 
- [x] @chrisjmendez 
- [ ] anyone else?

**Comment by jcblw** [comment]
✋ I can mentor again!

**Comment by d48** [comment]
:+1:

**Comment by davidguttman** [comment]
I'm in

**Comment by d48** [comment]
:+1:

**Comment by andyburke** [comment]
I would really like to make it to one of these. Right now my schedule's open. Let's do this. :facepunch:

**Comment by d48** [comment]
:+1:  :facepunch:

**Comment by emkay** [comment]
:gem: I'm in. :gem:

**Comment by chrisjmendez** [comment]
I can help. 👍🏽

**Comment by d48** [comment]
Fantastic. CodeSmith mentioned the prior week on September 19 to hold NodeSchool works better for their scheduling. Is this still doable for you all? 

@jcblw
@davidguttman
@andyburke
@emkay 
@chrisjmendez

**Comment by andyburke** [comment]
I believe so for me, yes.

**Comment by d48** [comment]
:+1:  awesome. How's everyone else? Once that's a go, we can reach out to our network and see who's willing to sponsor

**Comment by emkay** [comment]
That should be ok for me too.

**Comment by d48** [comment]
:+1:

**Comment by d48** [comment]
One last check for next Saturday the 19th and we can try to be aggressive at promoting it being at CodeSmith. 

The rest of those on the list, does this Saturday still work for you guys?

**Comment by andyburke** [comment]
works for me

**Comment by emkay** [comment]
dang unfortunately, I won't be able to make it.

**Comment by davidguttman** [comment]
I'm in.

**Comment by d48** [comment]
awesome, ready to do this. @emkay hopefully next time if it lines up
