### ISSUE TITLE
Anyone know any person/company willing to sponsor next NodeSchool event for September?

### ISSUE THREAD

**Issue by d48** [nodeschool/los-angeles#41]
Need to establish a sponsor or more for the next event. Does anyone know someone or company willing to sponsor and get some advertising for themselves?

**Comment by d48** [comment]
Basically would cover any sticker creation and basic snacks/drinks

**Comment by d48** [comment]
Are we okay with not having a sponsor for food and drink for this event?

**Comment by jcblw** [comment]
i think we should get js.la to sponsor lol. I can pitch in with the stickers since I want the new one :D

**Comment by d48** [comment]
@davidguttman @emkay  is this a possibility?

**Comment by d48** [comment]
We are good to go and have sponsors/support lined up. @jsdotla and @andyburke for the win!
