### ISSUE TITLE
Next seasons logo

### ISSUE THREAD

**Issue by jcblw** [nodeschool/los-angeles#42]
<img width="500" alt="screen shot 2015-08-30 at 4 18 29 pm" src="https://cloud.githubusercontent.com/assets/578259/9570057/067d901e-4f33-11e5-9978-2eb508018eec.png">

What do you think?

Also if we are daring we can switch around the color scheme as well.

<img width="732" alt="screen shot 2015-08-30 at 4 18 44 pm" src="https://cloud.githubusercontent.com/assets/578259/9570061/24129002-4f33-11e5-9ff2-302c19592407.png">

**Comment by sotayamashita** [comment]
It's cool !!!

**Comment by machikoyasuda** [comment]
i like the fall color scheme. gotta collect em all :)

**Comment by d48** [comment]
Awesome @jcblw. My only $.02 is to touch up the airplane silhouettes a little. These are cool from the LAX signage:

![signage](https://s-media-cache-ak0.pinimg.com/736x/0f/66/9c/0f669cc542542fd2111e0fcc504e8797.jpg)

**Comment by jcblw** [comment]
@d48  nice thanks those are nice

**Comment by d48** [comment]
@jcblw :+1:  

Was thinking since we may be changing these seasonally, the way you setup the site template can have a configuration for css also. Variables for:
* logo
* section background colors
* button colors
* headline colors

I can open an issue and see if anyone wants to take a stab at setting up the configuration

**Comment by jcblw** [comment]
@d48 right now we do have the color configurable,

https://github.com/nodeschool/los-angeles/blob/gh-pages/styles/less/base/_variables.less

Thats how i was able to mock up the site really fast with the new colors. The logo is another thing, I wondering how we can archive as well as update the logos. Right now I just added a suffix the the older logo in the repo.

**Comment by d48** [comment]
Awesome. I'm thinking if we can just dynamically create that .less file pulling in some .json file, before it compiles the css. The logos could then just be a css style and we archive via an array of those paths

**Comment by d48** [comment]
@jcblw if you're down, let's get those awesome new colors and logo in

**Comment by jcblw** [comment]
@d48 ok let me look at what else needs to be done i dont think much. It might just be tweeking colors a bit.

**Comment by d48** [comment]
@jcblw awesome. As always, great work as well

**Comment by rouzbeh84** [comment]
I think this one is all set! thanks for all the help & hard work 👍 

gonna close it out now 💯
