### ISSUE TITLE
conceptual resource for learnyounode and stream-adventure

### ISSUE THREAD

**Issue by cch5ng** [nodeschool/los-angeles#44]
hi, I just found this handy resource http://www.sitepoint.com/basics-node-js-streams/

I had gone through the learnyounode tutorial and passed the lessons but felt like it was missing some high level concepts to tie together what I was doing. also I felt like the concepts might be useful to the stream-adventure tutorial since I had not worked with unix pipes before.

hope this can be useful to other students. thanks. if this is not appropriate as an issue, just let me know and I'll place it on my blog.

**Comment by d48** [comment]
Awesome @cch5ng!

**Comment by d48** [comment]
@cch5ng add it to your blog and if you want also post in some Resources page in a Wiki on this repo
