### ISSUE TITLE
Need a ti.to ticket banner

### ISSUE THREAD

**Issue by d48** [nodeschool/los-angeles#46]
JS.la ti.to banner looks great. Would be nice to have one for NodeSchool LA ti.to tickets when people sign up. _halp_ :smile: 

![screenshot](http://content.screencast.com/users/Ryan.Regalado/folders/Jing/media/748c1b71-ccc5-4c2c-972b-f8eec254bbfe/00000425.png)

**Comment by jcblw** [comment]
lol, I made this. I dont have photoshop right now :/ or I would hook it up.

**Comment by d48** [comment]
Nice! Cool, let's see if anyone else can assist. Great work as always @jcblw

**Comment by d48** [comment]
this is not entirely needed, just a nice to have. I can close for now until someone wants to have a go at it

**Comment by cch5ng** [comment]
hi, I can work on this. I was playing around with typed.js and these are a few concepts I had.

https://cch5ng.github.io/anim-type/

the size and details and content can change (since they are on the page, maybe they don't need to be convinced to sign up). I was thinking about a banner sized ad but I can make the dimensions a bit more like the original banner. I will probably get back to this late next week but please send feedback and any requirements I should keep in mind (like do you want to keep to the same color palette as the index.html page).

**Comment by d48** [comment]
Awesome @cch5ng, going to take a look further and see any limitations on ti.to regarding banner files

**Comment by d48** [comment]
Hi @cch5ng, the ti.to banner is actually just an image and we probably just want something designed with the NodeSchool LA logo. You're more than welcome to try and design something for it. Here are the specs if you're interested:

`Banner image should be a JPEG, GIF or PNG, 900×265px (@1x) or 1800×530px (@2x)`

**Comment by cch5ng** [comment]
Thanks Ryan, I can create a graphic for the banner towards this weekend. It
can include and be more connected to the logo.

**Comment by d48** [comment]
👍

**Comment by rouzbeh84** [comment]
hi all! 

any progress on this or should I close again? thanks!

**Comment by ashwell** [comment]
I think this would still be nice to have :man_shrugging:

**Comment by rouzbeh84** [comment]
Same. How do y'all feel about the js.la standard banner with the sweet nodeschool logo on it??

**Comment by cch5ng** [comment]
hi, sorry for the delay. I had a couple of banner ideas. would either work? do you need text specific to NodeSchool LA? I think I need to fix the image dimensions (decrease), per https://github.com/nodeschool/los-angeles/issues/46#issuecomment-187440200.

![3d_lego](https://cloud.githubusercontent.com/assets/4755432/26085872/17a33a38-399c-11e7-8754-c2e608c9d8eb.jpg)

![node_owl2](https://cloud.githubusercontent.com/assets/4755432/26085879/21a932d0-399c-11e7-8d2d-460e91bbcf53.jpg)

**Comment by cch5ng** [comment]
hi, if it's alright, I think this issue could either be closed or later reassigned to another person. I feel I have too much on my plate to give a lot of time to it. perhaps the original image (yellow photo) could be used as a placeholder until another person is open to volunteer (?). I apologize again for having a lot of time pass between the original volunteer offer (I forgot about it after a while). thanks.

**Comment by jcblw** [comment]
no need to apologize @cch5ng you have already gone above and beyond 🚀 Thank you!

**Comment by rouzbeh84** [comment]
@cch5ng thanks for your work! I definitely should have been more specific on the request when I rekindled the conversation :(. Will close until time comes to revisit :)

**Comment by cch5ng** [comment]
@rouzbeh84 maybe if I had more commercial experience, it would have been easier to suss out a working concept more smoothly. but in the future, maybe it would be useful to provide a couple samples for the type of look/feel of interest. best wishes with it though 😀

**Comment by rouzbeh84** [comment]
No worries! Thanks for the submission and we will definitely have some better guidelines when we try to tackle this again 👏🏽
