### ISSUE TITLE
Event / Mentor checklist of 9/19/2015 - 1:30pm - 2:00pm

### ISSUE THREAD

**Issue by d48** [nodeschool/los-angeles#48]
For all those involved in coordinating and mentoring, please look below and mark if you can assist with any of the following. Below are some tips for mentoring as well if this is your first time.

**Mentors**
* @andyburke 
* @chrisjmendez
* @d48
* @davidguttman 
* @jcblw  (Will be MC for the event)
* @WillSen (Codesmith sponsor/talk)

## Food & Amenities
- [x]  @davidguttman to order and have delivered before event starts

## Workshop Prep
- [x] Name tags and markers. @d48 will bring

## Mentoring Tips
* **Do a workshopper**: Make sure you have done at least **learnyounode** so you can help others
* **Hover**: Mentors float around the event asking attendees if they are stuck, or if the attendees are too scared to ask for help then the mentors would try to peak over their shoulders and give them unsolicited advice.
* **Troubleshooting** : Don't give answers straight away if you know the bug or problem they are trying to solve. Instead guide them through the debugging process as this helps:
  1. Make the learner feel less incompetent and more like we're in this together because we both don't know what's going on, and 
  2. Give them the skills to find their own bugs when there aren't mentors around.
* And read through this thorough guide from the San Francisco chapter: https://github.com/nodeschool/sanfrancisco/wiki/Mentorship-Guidelines-and-Advice

## Schedule (tenative)
| Name | Time          | Description |
| :--- | :--- | :--- |
| Mentors check-in      | 1:30pm - 1:45pm | Come a little early if possible |
| Pre-event      | 1:30pm - 2:00pm | Will Sentance talk about applications of Node.js |
| Check-in / Snack and drink     | 2:00pm - 2:30pm     | Check list and hand out name tags, marker to write, Food and refreshments before we start |
| MC Welcome / Overview | 2:30pm - 2:40pm | Introduction and explain general setup of workshop install and mentor access, Given by @jcblw. Also Sponsor intro for 5 minutes: Codesmith and Float  |
| Workshop start | 2:45pm | Attendees installing/learning and asking mentors questions |
| Workshop end | 5:30pm | Let attendees know about 30 minutes. Final help and clean up. Take a picture! |
| Finish | 6:00pm | Go home |

**Comment by aktary** [comment]
I'll be there too.

**Comment by d48** [comment]
Awesome @aktary :+1:
