### ISSUE TITLE
Roll call for mentors at Saturday November 7 NodeSchool

### ISSUE THREAD

**Issue by d48** [nodeschool/los-angeles#49]
Who is willing and can make it? We are set to have CodeSmith host it for the first Saturdays in November and December.

- [x] @andyburke 
- [x] @aktary 
- [x] @Ashwell 
- [x] @davidguttman 
- [x] @jcblw 
- [ ] you?

**Comment by andyburke** [comment]
I believe I am available.

**Comment by aktary** [comment]
Me too.

Regards,

David Aktary

**Comment by Ashwell** [comment]
I'm available

**Comment by d48** [comment]
:+1:

**Comment by jcblw** [comment]
I can :hand:

**Comment by d48** [comment]
I think 5 is a good number to shoot for, for now. Will close this and update the readme. Thanks everyone
