### ISSUE TITLE
HEXDEX LA logo

### ISSUE THREAD

**Issue by jcblw** [nodeschool/los-angeles#5]
Hey guys,

So I know we plan to have another Nodeschool LA. So I was recently looking at the [HEXDEX](http://nodeschool.io/hexdex.html) and thought LA should have one! Here is what I came up with. I want you to guess what the building is. Let me know your thoughts.

![la-nodeschool](https://cloud.githubusercontent.com/assets/578259/5565921/217431c2-8ec5-11e4-8bd5-cd2285998c1c.png)
A1

**Comment by emkay** [comment]
Dang! totally missed this. Was just going to create an issue for logo ideas. I really like this.

**Comment by roobz** [comment]
I wanna say either the Helms Bakery or Griffith Observatory

**Comment by jcblw** [comment]
:+1: Griffith

**Comment by a0viedo** [comment]
woah looks really nice! :clap:

**Comment by christopherdro** [comment]
Very nice! Love the palm tree. 
Any thoughts on a color scheme different than one that already exists?

**Comment by jcblw** [comment]
@christopherdro I was going with a UCLAish / la county flag color schemes, but Im down to change it. Let me see what kinda of shape the SVG is in and ill share it here as well.

LA county flag ref.
![la county flag](http://upload.wikimedia.org/wikipedia/commons/2/2b/Flag_of_Los_Angeles_County,_California.png)

**Comment by christopherdro** [comment]
how about the city flag?
![Image of LA Flag]
(http://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Flag_of_Los_Angeles,_California.svg/1280px-Flag_of_Los_Angeles,_California.svg.png)

**Comment by jcblw** [comment]
oo that could be cool, here is the svg. :warning: it is kinda messy and I have been editing with inkscape. 

https://drive.google.com/a/js.la/file/d/0B4JTGHwM7VDnM2xwNjhTX29PNTg/view?usp=sharing

**Comment by christopherdro** [comment]
Cool thanks! I'm just gonna put some color schemes together without trying to tie it to anything specific. You wanna do a few as well then we can just have people vote or something?

**Comment by aktary** [comment]
I'd like to suggest a sunset theme... something with blue, pink, purple
skies and palm trees :)  I'm not an artist or I'd draw it myself.

**Comment by jcblw** [comment]
@christopherdro nice yeah Ill try and make some tonight. We can have them either on this issue or another and assign numbers to them or something like that and have people vote by :+1: {n}.

@aktary I like that idea.

**Comment by christopherdro** [comment]
Label your comps with A1, A2, etc... and i'll go with B1, B2, etc...

**Comment by christopherdro** [comment]
![IMAGE for LA-Hex]
(http://oi60.tinypic.com/2eanm15.jpg)

I decided to incorporate the 'Nodeschool' heading with just a quick color change. You think we should include this or leave it out?

**Comment by jcblw** [comment]
@christopherdro i would include it

**Comment by maxogden** [comment]
as a non los angeles resident I would have though it would be LAX rather than LAC (but I have no idea really)

**Comment by jcblw** [comment]
@maxogden yeah that would be more recognizable, and I guess the X does not really mean anything.

> Before the 1930s, existing airports used a two-letter abbreviation based on the weather stations at the airports. At that time, "LA" served as the designation for Los Angeles Airport. But with the rapid growth in the aviation industry the designations expanded to three letters c. 1947, and "LA" became "LAX." The letter "X" has no specific meaning in this identifier.

http://en.wikipedia.org/wiki/Los_Angeles_International_Airport#The_.22X.22_in_LAX 

I like it :+1:

**Comment by christopherdro** [comment]
Why not just go with LA and re do some of the badge to fit that. I think lax is way too associated with the airport. No?

**Comment by jcblw** [comment]
I think either is cool, @motdotla had the same suggestion.

**Comment by jcblw** [comment]
A2 ( A1 is the first )
![kuwi-nodeschool](https://cloud.githubusercontent.com/assets/578259/6141903/ad68c404-b161-11e4-9ab0-c9a5d203a61a.png)

inspiration
![inspiration](http://upload.wikimedia.org/wikipedia/en/7/79/STN_MTN_KAUAI_Childish_Gambino.png)

**Comment by jcblw** [comment]
A3
![sunset-nodeschool](https://cloud.githubusercontent.com/assets/578259/6142050/02b6794a-b164-11e4-9d04-60e1f216abd7.png)

@aktary like this?

**Comment by aktary** [comment]
Yes! LOVE it!!

- David

**Comment by christopherdro** [comment]
A4
![IMAGE of LA-Hex2]
(http://oi62.tinypic.com/mb623c.jpg)

**Comment by emkay** [comment]
> as a non los angeles resident I would have though it would be LAX rather than LAC (but I have no idea really)

:+1: for LAX

**Comment by d48** [comment]
@jcblw I really like this logo you did and think will stand out from the rest of the Hexdex logos. I'll post this up on the nodeschool/los-angeles website I'm trying to put together right now so everyone can view. I'll set it up in a way where we can change out the logos fairly easily.

![screenshot](https://cloud.githubusercontent.com/assets/578259/6142050/02b6794a-b164-11e4-9d04-60e1f216abd7.png)

**Comment by 8bitDesigner** [comment]
@jcblw - I'd love to get a grip of these printed up for our July event; any chance you can hit me back with the SVG for sticker?

**Comment by jcblw** [comment]
@8bitDesigner are you on [JS.LA Slack](http://js.la/slack) I posted the SVG version of the file in the #nodeschool channel. Its pinned. I tried to upload it here its not a supported image type.

**Comment by jcblw** [comment]
i think its safe to say this is resolved.
