### ISSUE TITLE
Mentoring for Hacker Fund?

### ISSUE THREAD

**Issue by aktary** [nodeschool/los-angeles#51]
Hacker Fund is looking for a few good mentors for their upcoming Hackathon on the weekend of the 24th (details at https://hacktoberfest.splashthat.com/).  I can't make it, but I'm hoping one of you guys can.  If so, please reach out directly to Justin at brezh@hacker.fund

Thanks!
- Dave

@8bitDesigner
@andyburke
@d48
@davidguttman
@dstokes
@emkay
@etanlubeck
@jcblw
@paigeful
@rynodivino
@soldair
@xbudex

**Comment by d48** [comment]
Awesome @aktary, looking into it

**Comment by d48** [comment]
Thanks for posting @aktary. Closing for now but please keep everyone updated for any other ones
