### ISSUE TITLE
Call for mentors for February 6 event

### ISSUE THREAD

**Issue by d48** [nodeschool/los-angeles#55]
Who's in?

- [x] @d48
- [x] @jcblw 
- [x] @8bitDesigner  
- [x] @upinthisjoynt
- [x] @motdotla 
- [ ] you?

**Comment by jcblw** [comment]
:hand:

**Comment by d48** [comment]
^ this guy right here is awesome :smile:

**Comment by 8bitDesigner** [comment]
Meeeee! (And possibly @dstokes, or @xbudex?)

**Comment by jcblw** [comment]
@motdotla you down to mentor?

**Comment by aktary** [comment]
Not sure I can mentor (got a newborn at home now), but I wanted to show you guys my new laptop cover that just happens to blend perfectly with our sticker design. (I'm hoping the attachment comes through.)



- David

**Comment by d48** [comment]
Attachment didn't come through but congrats @aktary on the newborn!

**Comment by d48** [comment]
@upinthisjoynt you down to mentor for this coming February 6?

**Comment by aktary** [comment]
Of course it didn't. Trying with imgur: http://imgur.com/J7QZo25

- David

**Comment by d48** [comment]
That looks awesome @aktary 

![screenshot](http://i.imgur.com/J7QZo25.jpg)

**Comment by upinthisjoynt** [comment]
Awe yea!

On Mon, Jan 11, 2016 at 2:17 PM, Ryan Regalado <notifications@github.com>
wrote:

> @upinthisjoynt <https://github.com/upinthisjoynt> you down to mentor for
> this coming February 6?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nodeschool/los-angeles/issues/55#issuecomment-170708885>
> .
>



-- 
*Addam Driver*
*DevCrapshoot.com <http://Dev.Crapshoot.com>*
*http://devcrapshoot.com <http://devcrapshoot.com>*

*"Controlling complexity is the essence of computer programming" ~ Brian
Kernighan*

**Comment by d48** [comment]
^ 💥 for @upinthisjoynt and @8bitDesigner

**Comment by motdotla** [comment]
Yeah, count me in to mentor!

http://mot.la

**Comment by d48** [comment]
Awesome @motdotla, I think we're good for mentors now since we have a cap of 60 students.

All, for some guidelines to follow when mentoring, [review these tips](https://github.com/nodeschool/los-angeles/issues/48) for now under **Mentoring Tips** 

Will follow up with some additional guidelines when the date gets closer for some things we will try based on the last couple of NodeSchool event feedback. Thank you everyone, all of you are making a great impact for the Node.js/JavaScript community in LA!
