### ISSUE TITLE
Fancy Website

### ISSUE THREAD

**Issue by emkay** [nodeschool/los-angeles#6]
http://nodeschool.io/los-angeles doesn't exist and it should.

**Comment by jcblw** [comment]
:+1:

**Comment by christopherdro** [comment]
Would love to contribute. Anyone already getting started?

**Comment by jcblw** [comment]
@christopherdro  no one has started, Im pretty sure if you would like to take a swing at it go ahead that would be awesome!

**Comment by emkay** [comment]
@christopherdro :+1: Go for it. 

https://github.com/nodeschool/organizers/blob/master/README.md#4

**Comment by christopherdro** [comment]
Sounds good guys. I'll probably start up on something towards the weekend.

**Comment by christopherdro** [comment]
@emkay: Any thoughts of working on this so we can gather donations to help us with some of the organization of setting up the chapter? 

@lorensstewart you think you can lend a hand with this if we agree to move forward with this? I would assist as well.

http://www.calnonprofits.org/resources/starting-nonprofit/15-launch-articles/65-first-steps-articl#actions

**Comment by lorensstewart** [comment]
@christopherdro I can definitely help with this.

**Comment by emkay** [comment]
@christopherdro I don't think we need to setup a non-profit. The overhead doesn't seem worth it. We've already ran a NodeSchool event back in November, we just didn't get the website setup.

**Comment by christopherdro** [comment]
cool

**Comment by d48** [comment]
Hello everyone,

Just to introduce myself, I'm Ryan from the LA area. I'm at Nodeconf 2015 in Petaluma, CA right now and getting really inspired to help boosting the Node.js/JavaScript/hacking community in Los Angeles.  Trying to set up a nodeschool.io/losangeles website now via `gh-pages` branch. I'm basically going to cover:

* Website that announces we exist :smiley: 
* Placeholder for next event date with link to http://ti.to
* Provide overview of Nodeschool with links to main site and to some sort of boiler-plate Code of Conduct
* Link to [questions](https://github.com/nodeschool/los-angeles/issues/) and link to overview of Git and Github; similar to [Nodeschool/Berling](http://nodeschool.io/berlin/)

Any other needs you think, please chime in else we can just hack at it for what's needed after the first iteration. Thanks guys.

**Comment by jcblw** [comment]
@d48 you are awesome my friend!

**Comment by d48** [comment]
:+1:

**Comment by d48** [comment]
Here's a couple links to a sample and working version. Let me know what you guys think: http://blog.design48.net/los-angeles/

git branch on my forked repo: https://github.com/d48/los-angeles/tree/gh-pages

I think I would be able to create a pull-request if someone with access can create a `gh-pages` on this repo

![screenshot](http://f.cl.ly/items/2j301l3h29050A0A3r2b/screenshot-nodeschool-los-angeles-website.png)

**Comment by emkay** [comment]
@d48 :+1: you should have access.

**Comment by d48** [comment]
Awesome, thanks @emkay

**Comment by d48** [comment]
Just opened up a pr if anyone can have a look-over and comment/merge. Thanks!
