### ISSUE TITLE
Call for mentors for March 5 event

### ISSUE THREAD

**Issue by d48** [nodeschool/los-angeles#62]
Who's in?

- [x] @d48
- [x] @stefansundin 
- [x] @ashwell 
- [x] @MrSkinny 
- [x] @upinthisjoynt

**Comment by stefansundin** [comment]
:hand:

**Comment by ashwell** [comment]
:+1:

**Comment by MrSkinny** [comment]
Sign me up!

**Comment by d48** [comment]
sweet! need one more. @upinthisjoynt, you in?

**Comment by upinthisjoynt** [comment]
I'm in

**Comment by d48** [comment]
awesome everyone! I will follow up with another message next week on what to prepare for and what the schedule looks like. See you guys then and thanks again for your time, the attendees super appreciate it

**Comment by Rrrapture** [comment]
I'm in!

**Comment by d48** [comment]
Thanks @Rrrapture! adding you to the list

**Comment by d48** [comment]
adding @jcblw to the list also
