### ISSUE TITLE
April 2nd NodeSchool Mentor roll call

### ISSUE THREAD

**Issue by d48** [nodeschool/los-angeles#66]
Will you be a mentor and assist others in learning Node.js? Come join this April 2nd.

- [x] @d48
- [x] @jcblw 
- [x] @upinthisjoynt 
- [x] @Rrrapture 
- [x] @etanlubeck 
- [ ] you?

**Comment by jcblw** [comment]
:hand:

**Comment by d48** [comment]
awesome. @8bitDesigner @upinthisjoynt?

**Comment by upinthisjoynt** [comment]
IN

**Comment by Rrrapture** [comment]
I'm in!

**Comment by 8bitDesigner** [comment]
I wish, but I have, I kid you not, three different birthday parties that I'm already committed to that day. Have a great time, and I hope to catch up with you all in April!

**Comment by d48** [comment]
sweet @Rrrapture, cool @8bitDesigner

**Comment by d48** [comment]
5 mentors is good. Will follow up with day plan early next week. Thanks everyone.
