### ISSUE TITLE
Event / Mentor checklist for 04/02/2016 event

### ISSUE THREAD

**Issue by d48** [nodeschool/los-angeles#67]
## Mentors
Below are some tips for mentoring as well if this is your first time.

@d48
 @jcblw
 @upinthisjoynt
 @Rrrapture
 @etanlubeck

## Food & Amenities
- [x] Order and have delivered before event starts. @d48 

## Workshop Prep
- [x] Name tags and markers. @d48 will bring

## Mentoring Tips
* **Do a workshopper**: Make sure you have done at least **learnyounode** so you can help others
* **Hover**: Mentors float around the event asking attendees if they are stuck, or if the attendees are too scared to ask for help then the mentors would try to peak over their shoulders and give them unsolicited advice.
* **Troubleshooting** : Don't give answers straight away if you know the bug or problem they are trying to solve. Instead guide them through the debugging process as this helps:
  1. Make the learner feel less incompetent and more like we're in this together because we both don't know what's going on, and 
  2. Give them the skills to find their own bugs when there aren't mentors around.
* And read through this thorough guide from the San Francisco chapter: https://github.com/nodeschool/sanfrancisco/wiki/Mentorship-Guidelines-and-Advice
* **Organizing attendees**: Based on previous feedback, attendees would feel comfortable and can potentially perform better if grouped together with people doing the same workshoppers. If we can, setting up tables in a triangle has worked very well in the past. We will have a show of hands of which attendees will be doing what and we will do a seating shuffle at that point.

## Schedule (tenative)
| Name | Time          | Description |
| :--- | :--- | :--- |
| Mentors check-in      | 1:30pm - 1:45pm | Come a little early if possible. Will review with how we will organize attendees based on workshopper/experience.  |
| Check-in / Snack and drink     | 2:00pm - 2:30pm     | Check list and hand out name tags, marker to write, Food and refreshments before we start |
| MC Welcome / Overview | 2:15pm - 2:30pm | Introduction and explain general setup of workshop install and mentor access. Also Sponsor intro for 5 minutes: CodeSmith. Node.js overview and sample uses (@upinthisjoynt)  |
| Workshop start | 2:30pm | Attendees installing/learning and asking mentors questions |
| Group pic | 4:30pm | Take a picture! |
| Workshop end | 5:30pm | Let attendees know about 30 minutes. Final help and clean up. |
| Finish | 6:00pm | Go home |

**Comment by d48** [comment]
Thanks mentors! setting up for next event now

**Comment by upinthisjoynt** [comment]
IN!

On Tue, Apr 19, 2016 at 10:16 AM, Ryan Regalado <notifications@github.com>
wrote:

> Thanks mentors! setting up for next event now
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/nodeschool/los-angeles/issues/67#issuecomment-212023738>
>



-- 
*Addam Driver*
*DevCrapshoot.com <http://Dev.Crapshoot.com>*
*http://devcrapshoot.com <http://devcrapshoot.com>*

*"Controlling complexity is the essence of computer programming" ~ Brian
Kernighan*
