### ISSUE TITLE
In-person workshoppers

### ISSUE THREAD

**Issue by lorensstewart** [nodeschool/los-angeles#7]
Are there any plans for an in-person workshopper anytime soon?

**Comment by emkay** [comment]
Hey @lorensstewart we have started talking about the next event, but no details are settled. Do you have any suggestions about hosts, etc.?

**Comment by lorensstewart** [comment]
@emkay : I haven't organized anything like this, so I don't have any suggestions. However, I have a lot of energy and would be happy to help! All I need is a little direction.

**Comment by emkay** [comment]
No worries! Yeah will update back here when we have more info.

**Comment by d48** [comment]
@lorensstewart coming up on July 25! hope to see you there: http://nodeschool.io/los-angeles

**Comment by lorensstewart** [comment]
I've been silently excited over here as things kicked into gear this week. I'll definitely be there on the 25th!!



—

**Comment by d48** [comment]
nice :+1:
