### ISSUE TITLE
Mentor roll call for May 7 NodeSchool

### ISSUE THREAD

**Issue by d48** [nodeschool/los-angeles#70]
This is a call for anyone that is willing to mentor next month. Are you in?

- [x] @d48 
- [x] @etanlubeck 
- [x] @upinthisjoynt
- [x] @jcblw 
- [x] @ashwell

**Comment by jcblw** [comment]
✋

**Comment by d48** [comment]
nice

**Comment by d48** [comment]
@ashwell you coming to join this day?

**Comment by ashwell** [comment]
Hey! Sorry @d48, yeah I should be able to make it

**Comment by d48** [comment]
no worries @ashwell, awesome! will add you to the list and close this

**Comment by d48** [comment]
thanks guys, will follow up with schedule for the day

**Comment by ashwell** [comment]
@d48 looks like we have a late addition to the party,

https://github.com/nodeschool/los-angeles/pull/72

**Comment by d48** [comment]
Sweet, I'll be sending mentor correspondence shortly
