### ISSUE TITLE
Mentor roll call for June 4, 2016 event

### ISSUE THREAD

**Issue by d48** [nodeschool/los-angeles#78]
This is a call for anyone that is willing to mentor this Saturday. Are you in?

- [x] @jcblw
- [x] @d48
- [x] @ashwell
- [x] @etanlubeck
- [ ] you?

**Comment by jcblw** [comment]
lol I was about to the the you? check box.

**Comment by d48** [comment]
hah, added

**Comment by etanlubeck** [comment]
is it at codesmith or makersquare?

**Comment by ashwell** [comment]
I believe I already registered

**Comment by d48** [comment]
it's at CodeSmith for this Saturday

**Comment by etanlubeck** [comment]
i'm in

**Comment by d48** [comment]
this should be good enough for the size of the group. thanks guys, will follow up with day schedule
