### ISSUE TITLE
Mentor roll call for July 2nd event

### ISSUE THREAD

**Issue by d48** [nodeschool/los-angeles#81]
This is a call for anyone that is willing to mentor this Saturday. Are you in?

- [x] @d48
- [x] @ashwell 
- [x] @jcblw  
- [ ] you?

**Comment by ashwell** [comment]
Hey @d48 I'll be able to make it this month, but I'm going to have to leave around 4:30 - 5

**Comment by d48** [comment]
awesome. need a few more mentors for this day

@etanlubeck 
@jcblw 
@davidguttman 

?

**Comment by jcblw** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/7681590-137218884_3-s1-v1.png?palette=1&width=246)

**Comment by andyburke** [comment]
I would really like to make it to one of these again sometime soon. Unfortunately I can't do this saturday. :(

**Comment by d48** [comment]
awesome @jcblw and @andyburke

**Comment by d48** [comment]
okay, let's try with 3 mentors. I think we should be ok. Thanks guys, see you tomorrow
