### ISSUE TITLE
Mentor roll call for August 6, 2016 event at NodeBots

### ISSUE THREAD

**Issue by d48** [nodeschool/los-angeles#84]
This August NodeSchool will be at the NodeBots event being sponsored by CAA:
http://nodebotsday.caa.com/

We will be going over the properly themed NodeBot workshop: https://github.com/tableflip/nodebot-workshop

Are you in? Specific time slot will be determined as we get closer to the date, but expect a 3-4 hour block.

- [x] @d48
- [x] @etanlubeck 
- [x] @ashwell 
- [x] @jcblw 
- [ ] you?

**Comment by d48** [comment]
@ashwell 
@jcblw 
@davidguttman 

any of you guys in?

**Comment by ashwell** [comment]
hey sorry I've dropped the ball on this, I'm planning to be at nodebots all day

**Comment by jcblw** [comment]
ditto

**Comment by d48** [comment]
awesome, will add you guys. @etanlubeck do you know the schedule for the day by any chance so we can see where NodeSchool event can start and in what area/room?

**Comment by etanlubeck** [comment]
here is the schedule: 
Order of Activities
·         7:00 Setup
·         8:30 Breakfast/Doors open for registration
·         9:00 - Coding Starts/Challenge Open
·         12:00 - Lunch
·         2:00 Product Development Grp Talk
·         3:00 - Demonstrations
·         4:30 - Awards
·         5:00 - Closing/Clean Up

**Comment by etanlubeck** [comment]
@d48

**Comment by d48** [comment]
Thanks Nate. I assume we will have NodeSchool running at the time people are then just coding from 9am through lunch all the way to 3pm?

**Comment by d48** [comment]
Was a cool event! No need for NodeSchool but thinking it would be great for a future NodeSchool day to have some boards and coding if someone wanted to fiddle with Johnny-Five workshopper
