### ISSUE TITLE
Mentor roll call for October 1st event at Codesmith

### ISSUE THREAD

**Issue by d48** [nodeschool/los-angeles#92]
Who would like to help mentor for this event?

- [x] @d48 
- [x] @jcblw 
- [x] @ashwell 
- [x] Jean-Pierre
- [ ] you?

**Comment by ashwell** [comment]
@etanlubeck were you going to make it to this one?

**Comment by etanlubeck** [comment]
I'm already on the mentor list. oh I didn't add it to this issue. yah I'll be there

**Comment by ashwell** [comment]
cool, making a PR to update the readme now

**Comment by d48** [comment]
there's another volunteer that wanted to join as well. I'll just add his name if he forward me his github account

**Comment by d48** [comment]
Thanks guys, closing this and following up with schedule for the day
