### ISSUE TITLE
Mentor roll call for November 5, 2016 event at Codesmith

### ISSUE THREAD

**Issue by d48** [nodeschool/los-angeles#98]
Who's in to mentor for this event? 
- [x] @etanlubeck 
- [x] @ashwell 
- [x] @jcblw  
- [ ] you?

**Comment by d48** [comment]
@jcblw @ashwell are you guys in for this month?

**Comment by ashwell** [comment]
I should be able to make it out

**Comment by jcblw** [comment]
ill be able to make it too

**Comment by d48** [comment]
Sweet, I'll add you guys. I'm not able to make it out this weekend but @etanlubeck is handling MCing
